// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tourist.Domain.Data;

#nullable disable

namespace Tourist.Domain.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625102241_InitialDomain")]
    partial class InitialDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tourist.Domain.Entities.Attraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("TourRouteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourRouteId");

                    b.ToTable("Attractions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Замково-парковый комплекс XVI века, объект ЮНЕСКО",
                            Name = "Мирский замок",
                            TicketPrice = 15m,
                            TourRouteId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Дворцово-парковый комплекс рода Радзивиллов",
                            Name = "Несвижский замок",
                            TicketPrice = 15m,
                            TourRouteId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Средневековый замок XIV века",
                            Name = "Лидский замок",
                            TicketPrice = 7m,
                            TourRouteId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Неоготический дворец XIX века",
                            Name = "Коссовский замок",
                            TicketPrice = 5m,
                            TourRouteId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Исторический центр Минска с Ратушей",
                            Name = "Верхний город",
                            TicketPrice = 0m,
                            TourRouteId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Исторический район Минска",
                            Name = "Троицкое предместье",
                            TicketPrice = 0m,
                            TourRouteId = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "Мемориальный комплекс воинам-интернационалистам",
                            Name = "Остров слёз",
                            TicketPrice = 0m,
                            TourRouteId = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "Древнейший лес Европы, объект ЮНЕСКО",
                            Name = "Беловежская пуща",
                            TicketPrice = 25m,
                            TourRouteId = 3
                        },
                        new
                        {
                            Id = 9,
                            Description = "Интерактивный музей о флоре и фауне",
                            Name = "Музей природы",
                            TicketPrice = 10m,
                            TourRouteId = 3
                        },
                        new
                        {
                            Id = 10,
                            Description = "Резиденция белорусского Деда Мороза",
                            Name = "Поместье Деда Мороза",
                            TicketPrice = 12m,
                            TourRouteId = 3
                        },
                        new
                        {
                            Id = 11,
                            Description = "Мемориальный комплекс",
                            Name = "Брестская крепость-герой",
                            TicketPrice = 0m,
                            TourRouteId = 4
                        },
                        new
                        {
                            Id = 12,
                            Description = "Музей с экспонатами об обороне 1941 года",
                            Name = "Музей обороны Брестской крепости",
                            TicketPrice = 8m,
                            TourRouteId = 4
                        },
                        new
                        {
                            Id = 13,
                            Description = "Один из старейших городов Беларуси",
                            Name = "Пинск",
                            TicketPrice = 5m,
                            TourRouteId = 5
                        },
                        new
                        {
                            Id = 14,
                            Description = "Древнейший город Беларуси X века",
                            Name = "Туров",
                            TicketPrice = 3m,
                            TourRouteId = 5
                        },
                        new
                        {
                            Id = 15,
                            Description = "Уникальный заповедник с болотами Полесья",
                            Name = "Национальный парк Припятский",
                            TicketPrice = 10m,
                            TourRouteId = 5
                        });
                });

            modelBuilder.Entity("Tourist.Domain.Entities.TourRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("TourRoutes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Путешествие по средневековым замкам страны",
                            Name = "Замки Беларуси",
                            NormalizedName = "zamki"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Столица Беларуси и её достопримечательности",
                            Name = "Минск и окрестности",
                            NormalizedName = "minsk"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Древнейший лес Европы и национальный парк",
                            Name = "Беловежская пуща",
                            NormalizedName = "belovezhskaya-pushcha"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Мемориальный комплекс и крепость-герой",
                            Name = "Брестская крепость",
                            NormalizedName = "brest"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Уникальный край болот, лесов и древних городов",
                            Name = "Полесье",
                            NormalizedName = "polesye"
                        });
                });

            modelBuilder.Entity("Tourist.Domain.Entities.Attraction", b =>
                {
                    b.HasOne("Tourist.Domain.Entities.TourRoute", "TourRoute")
                        .WithMany("Attractions")
                        .HasForeignKey("TourRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TourRoute");
                });

            modelBuilder.Entity("Tourist.Domain.Entities.TourRoute", b =>
                {
                    b.Navigation("Attractions");
                });
#pragma warning restore 612, 618
        }
    }
}
